name: switas
base: core18
version: '0.0.1'
icon: share/icons/switas/logo/main.png
license: MIT
summary: A TAS toolkit for the Nintendo Switch
description: |
  A TAS toolkit, taking advantage of hardware, homebrew, and emulators,
  designed for the Nintendo Switch

# To build the snap, run `sudo snapcraft --use-lxd --enable-experimental-package-repositories`

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64
    
  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf
    
  - build-on: arm64
    run-on: arm64

parts:
  switas:
    plugin: make
    makefile: Makefile
    source: .
    make-parameters: ["-B", "BUILD=release"]
    artifacts:
      - bin/switas
      - share
      - mainSettings.json
    # stage:
    #   - ./*
    #   - ../sharedNetworkCode/*
    # organize:
    #   release/bspinfo: bin/bspinfo3
    #   release/qbsp3: bin/
    #   release/qdata: bin/
    #   release/qrad3: bin/
    #   release/qvis3: bin/
    # Need some of this lol https://forum.snapcraft.io/t/building-a-snap/13556/13
    # https://gist.github.com/ZachBacon/b4c76c3111c5dcb3c166c27ed1912aec
    stage-packages:
      - zlib1g
      - libgtk-3-0
      - libwxbase3.1-0-unofficial3
      - libwxgtk3.1-0-unofficial3
      - wx-common
      # Libraries suggested by Snap
      - libavcodec57
      - libavformat57
      - libavresample3
      - libavutil55
      - libbluray2
      - libchromaprint1
      - libcrystalhd3
      - libdrm2
      - libffms2-4
      - libgl1
      - libglvnd0
      - libglx0
      - libgme0
      - libgomp1
      - libgsm1
      - libice6
      - libluajit-5.1-2
      - libmp3lame0
      - libmpg123-0
      - libnotify4
      - libnuma1
      - libogg0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libshine3
      - libsm6
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample2
      - libswscale4
      - libtheora0
      - libtwolame0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx5
      - libwavpack1
      - libwebp6
      - libwebpmux3
      - libx264-152
      - libx265-146
      - libxtst6
      - libxvidcore4
      - libxxf86vm1
      - libzvbi0
    build-packages:
      - make
      - build-essential
      - gcc-9
      - g++-9
      - pkg-config
      - libwxbase3.1-0-unofficial3
      - libwxgtk3.1-0-unofficial3
      - libwxbase3.1unofficial3-dev
      - libwxgtk3.1unofficial3-dev
      - wx-common
      - libsm6
      - libnotify4
      - libxtst6
      - libffms2-dev
      - libluajit-5.1-dev
    # Install gcc-9
    override-build: |
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
      snapcraftctl build

apps:
  switas:
    # desktop-launch /snap/bin/switas
    command: desktop-launch /snap/bin/switas
    extensions: [gnome-3-28]

package-repositories:
  - type: apt
    deb-types: [deb]
    components: [universe]
    suites: [$SNAPCRAFT_APT_RELEASE]
    url: http://repos.codelite.org/wx3.1.3/ubuntu/
    key-id: CodeLite

  - type: apt
    ppa: ubuntu-toolchain-r/test